name: sopi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.1.2
  provider: ^5.0.0
  http: ^0.13.1
  flutter_phoenix: ^1.0.0

  font_awesome_flutter: ^9.0.0
  flutter_speed_dial: ^3.0.5 # floating action button
  modal_bottom_sheet: ^2.0.0 # bottom sheet dialog
  lottie: ^1.0.1 # read animations type json
  timeline_tile: 2.0.0
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  flutter_native_splash: ^1.1.7+1
  flutter_form_builder: ^6.0.0-nullsafety.1
  firebase_storage: ^8.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  toggle_switch: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/animations/
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
