name: sopi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  http: ^0.12.0+2
  flutter_form_builder: ^4.2.0
  font_awesome_flutter: ^8.11.0
  cupertino_icons: ^0.1.2
  enum_to_string: ^1.0.9
  firebase_auth: ^0.20.0+1
  firebase_database: ^6.0.0
  firebase_core: ^0.7.0
  shared_preferences: ^0.5.7+3
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
