name: sopi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.25.4
  provider: ^4.0.4
  http: ^0.12.0+2
  intl: ^0.16.1
  flutter_form_builder: ^4.2.0
  font_awesome_flutter: ^8.11.0
  flutter_speed_dial: ^2.1.1 # floating action button
  enum_to_string: ^1.0.9
  shared_preferences: ^0.5.7+3
  flutter_native_splash: ^0.3.0
  firebase_storage: ^7.0.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0

  image_cropper: ^1.3.1
  image_picker: ^0.6.7+22


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
